### ISSUE TITLE
Unable to cast UInt64 to DateTime at Azure.Messaging.ServiceBus.ServiceBusReceivedMessage.get_LockedUntil()

### ISSUE THREAD

**Issue by lars-houtman** [mxsdev/LocalSandbox#68]
When receiving a message via a Processor, the value in the LockedUntil member of the message arriving in the ServiceBus SDK is not castable to a DateTime as it is a UInt64:
This happens here:
![image](https://github.com/user-attachments/assets/d26404ed-b62c-4abc-b493-06c7c08c5d74)

The value is brought in like this:
![image](https://github.com/user-attachments/assets/9deedd1a-1340-4981-a565-2e745f566185)

Causing the following stacktrace:
```
System.InvalidCastException: Unable to cast object of type 'System.UInt64' to type 'System.DateTime'.
   at Azure.Messaging.ServiceBus.ServiceBusReceivedMessage.get_LockedUntil()
   at Azure.Messaging.ServiceBus.CancellationTokenSourceExtensions.CancelAfterLockExpired(CancellationTokenSource cancellationTokenSource, ServiceBusReceivedMessage receivedMessage)
   at Azure.Messaging.ServiceBus.ProcessMessageEventArgs..ctor(ServiceBusReceivedMessage message, ReceiverManager manager, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ProcessMessageEventArgs..ctor(ServiceBusReceivedMessage message, ReceiverManager manager, String identifier, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ReceiverManager.ConstructEventArgs(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken)
```

This leads to the message being sent to the error eventhandler immediately without being able to process it.

If you require more info, please let me know

**Comment by lars-houtman** [comment]
Update: an "actual" servicebus returns the value in a string format:
![image](https://github.com/user-attachments/assets/61aeee40-4c47-4807-952e-8dcdfbd7e733)
